name: zeus_breakout_rivival
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.9.1
  flame_audio: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fvm: ^2.0.0
  flame: 1.7.3
  google_fonts: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
